settings:
  commit_msg: "Automatic workflow run update"
  max_lines: 10
  commit_username: "workflow"
  date:
    timezone: "+08:00"
  messages:
    added_member: "ğŸ¤ Became a collaborator on {REPO}"
    create_repo: "ğŸ“” Created {REPO}"
    issue_issue: "â—ï¸ Opened {ID} in {REPO}"
    issue_closed: "âœ”ï¸ Closed {ID} in {REPO}"
    new_release: "âœŒï¸ Released v{ID} for {REPO}"
    pr_merged: "ğŸ‰ Merged {ID} in {REPO}"
    create_wiki: "ğŸ“– Created wiki {WIKI} in {REPO}"
    new_star: "â­ Starred {REPO}"
    
